Repository woowa-techcamp-2020/market-13, pull requests merged in 2020-07, with the labels that each got.

#15 회원가입 페이지 마크업과css 작성\n 기획서에 따라 회원가입 페이지의 ui의css와 마크업 태그를 작성했습니다.
  bamin-13/frontend/complete.html
  bamin-13/frontend/css/alert.css
  bamin-13/frontend/css/default.css
  bamin-13/frontend/css/signup.css
  bamin-13/frontend/images/logo.png
  bamin-13/frontend/index.html
  bamin-13/frontend/login.html
  bamin-13/frontend/signup.html
  bamin-13/modules/jwt.js
  bamin-13/package.json
Labels: css, feature, frontend, layout

#22 메인 / 로그인 / 회원가입 완료 페이지 마크업 완료
  bamin-13/public/scripts/complete.js
  bamin-13/public/scripts/main.js
  bamin-13/public/stylesheets/complete.css
  bamin-13/public/stylesheets/main.css
  bamin-13/views/complete.pug
  bamin-13/views/login.pug
  bamin-13/views/main.pug
Labels: frontend, layout

#30 다음 주소 api 연동 및 선택 정보 콤보박스 토글기능 추가
  bamin-13/public/scripts/modal.js
  bamin-13/public/scripts/signup.js
  bamin-13/public/scripts/utils.js
  bamin-13/public/stylesheets/signup.css
  bamin-13/views/signup.pug
Labels: css, feature, frontend, layout

#38 Css change
  bamin-13/public/scripts/modal.js
  bamin-13/public/scripts/signup.js
  bamin-13/public/stylesheets/modal.css
  bamin-13/public/stylesheets/signup.css
  bamin-13/public/stylesheets/signup2.css
  bamin-13/routes/api/phone-auth.js
  bamin-13/routes/index.js
  bamin-13/views/signup.pug
  bamin-13/views/signup2.pug
Labels: css, enhancement, frontend, layout

#44 로그인 페이지 구현
  bamin-13/public/scripts/login.js
  bamin-13/public/stylesheets/main.css
  bamin-13/routes/index.js
  bamin-13/views/login.pug
Labels: frontend

#46 Link validation
  bamin-13/public/scripts/login.js
  bamin-13/public/scripts/signup.js
  bamin-13/public/scripts/utils.js
  bamin-13/public/stylesheets/main.css
  bamin-13/public/stylesheets/signup.css
  bamin-13/views/signup.pug
Labels: backend, feature

#50 인증완료시 버튼 css 변경 기능구현 완료
  bamin-13/modules/woowadb.js
  bamin-13/public/scripts/signup.js
Labels: enhancement, feature, frontend

#56 Fix issues
  bamin-13/public/scripts/signup.js
  bamin-13/public/stylesheets/modal.css
  bamin-13/views/complete.pug
  bamin-13/views/signup.pug
Labels: bug, enhancement, frontend
